### ISSUE TITLE
request to make `(boxType BoxType) getBoxDef(ctx Context)` public

### ISSUE THREAD

**Issue by mattetti** [abema/go-mp4#126]
First off, thanks for a great and flexible mp4 package. 
I'd like to use the package but I'd rather use lower APIs than parsing the file multiple times using `mp4.ExtractBoxWithPayload`. 

So I was thinking about using `mp4.ReadBoxStructure` and look at each atom and parse them one by one, based on what I need.
Something like what you did for https://github.com/abema/go-mp4/blob/master/mp4tool/divide/divide.go but without using `mp4.ExtractBox` / `mp4.ExtractBoxWithPayload`. For that, I need to be implement the equivalent of `Unmarshal` https://github.com/abema/go-mp4/blob/master/marshaller.go#LL265C12-L265C12 

To do that, I need to get the `boxDef`: `boxDef := dst.GetType().getBoxDef(ctx)` which would also require making the `boxDef` type public `https://github.com/abema/go-mp4/blob/master/mp4.go#L52`

I know it's a big request, and there might be a better way/API, but I hope you'd consider exposing a lower level API for people like me :)

Summary, making `getBoxDef` -> `GetBoxDef` and `boxDef` -> `BoxDef` (+ exported fields) would allow to leverage the library slightly differently.

```go
func (boxType BoxType) getBoxDef(ctx Context) *boxDef
```

**Comment by sunfish-shogi** [comment]
@mattetti 

> I'd like to use the package but I'd rather use lower APIs than parsing the file multiple times using mp4.ExtractBoxWithPayload.

ExtractBox, ExtractBoxes, ExtractBoxeWithPayload, and ExtractBoxesWithPayload are wrapper of ReadBoxStructure.
These functions will extract target boxes by depth-first search, but any boxes which do not match with specified paths will be skipped using  seek-operation.
If you want to read shallow box at first and read descendant boxes after that, you can specify start position into argument of secondary call.
If you do not need step-by-step (or streaming) operation, performance contribution by using ReadBoxStructure directly is restrictive.
Because, implementing properly, inefficient operation which reading same byte range twice is not occured.

> So I was thinking about using mp4.ReadBoxStructure and look at each atom and parse them one by one, based on what I need.
> Something like what you did for https://github.com/abema/go-mp4/blob/master/mp4tool/divide/divide.go but without using mp4.ExtractBox / mp4.ExtractBoxWithPayload. For that, I need to be implement the equivalent of Unmarshal https://github.com/abema/go-mp4/blob/master/marshaller.go#LL265C12-L265C12
> To do that, I need to get the boxDef: boxDef := dst.GetType().getBoxDef(ctx) which would also require making the boxDef type public https://github.com/abema/go-mp4/blob/master/mp4.go#L52

Is root of the problem is performance of Unmarhsal?
If you need to read only specific bytes using custom implementation instead of Unmarshal, any new interface is maybe required like your suggestion.
But, if main cause is the file I/O performance, the most effective improvement is buffering.
